var natwest = {
    $primary_2 : "rgb(255, 255, 255)",
    $col_block1_bg: "rgba(206, 59, 87, 1)",
    $col_block1_yellow_bg:"rgba(251, 186, 32, 1)",
    $font_family_bold:"RNHouseSansBold, sans-serif",
    $font_family_regular: "RNHouseSansRegular, sans-serif",
    $font_color_regular:"rgb(44, 6, 55)",
    $primary_white_smoke:"rgb(255, 255, 255)",
    $font_family_bold:"RNHouseSansLight, sans-serif",
    $font_family_light:"RNHouseSansLight, sans-serif",
    $font_weight: "normal",
    $cookie_bgColor: "rgba(44, 6, 55, 1)",
    $font_family_text: "RNHouseSansLight, sans-serif",
    $font_family_cta: "RNHouseSansRegular, sans-serif",
    $cookie_close_color:"rgba(255, 0, 0, 1)",
     $font_family_title:"RNHouseSansLight, sans-serif",
    $body_letter_spacing:"0.3px",
    $impFigText:"rgb(149, 107, 90)",
    $borderbottomcolor:"1px solid rgb(229, 216, 211)",
    $accContmPadding:"35px",
    $acc_contText_color: "rgb(51, 51, 51)",
    $color:"rgb(255, 255, 255)",
    $colorBlack:"rgb(51, 51, 51)",
    $marginTopAcc : "6px",

     //yellow toggle variables
    $yellow_toggle_color:"rgb(251, 186, 32, 1)",
    $border_top_left_radius:"0px",
    $border_bottom_left_radius:"0px",
    $border_radius:"1px solid rgba(66, 20, 95, 1)",
      //title wrap rose
    $rose_title_wrap_mt_xl:"50px",
     $rose_title_wrap_mt_xs:"30px",
      //title text
      $font_weight_title_text:"normal",
      //title wrap5 variables
     $title_wrap_mt_xl:"50px",
     $title_wrap_mt_l:"40px",
     $title_wrap_mt_xs:"30px",
     //XL Styles
    $h1_font_size_xl:"52px",
    $h1_line_height_xl:"64px",
    $h2_cust_font_size_xl:"40px",
    $h2_cust_line_height_xl:"50px",
    $h3_cust_font_size_xl:"26px",
    $h3_cust_line_height_xl:"34px",
    $h3_font_size_xl:"30px",
    $h3_line_height_xl:"40px",
    $h4_font_size_xl:"22px",
    $h4_line_height_xl:"30px",

    //L Styles
    $h1_font_size_l:"42px",
    $h1_line_height_l:"54px",
    $h2_cust_font_size_l:"38px",
    $h2_cust_line_height_l:"48px",
    $h3_font_size_l:"26px",
    $h3_line_height_l:"36px",
    $h3_cust_font_size_l:"24px",
    $h3_cust_line_height_l:"32px",    

    //M Styles
    $h1_font_size_m:"34px",
    $h1_line_height_m:"44px",
    $h2_cust_font_size_m:"28px",
    $h2_cust_line_height_m:"38px",
    $h3_font_size_m:"24px",
    $h3_line_height_m:"32px",
    

    //S Styles
    $h1_font_size_s:"34px",
    $h1_line_height_s:"44px",
    $h2_cust_font_size_s:"34px",
    $h2_cust_line_height_s:"44px",
    $h3_font_size_s:"24px",
    $h3_line_height_s:"32px",
    
    //legal-copy styles
    $legal_copy_font_size:"16px",
    $legal_copy_line_height:"26px",

    //bg color variable
    $main_bg : "rgba(0, 159, 172, 1)",
    $viomain_bg : "rgba(66, 20, 95, 1)",
    $title_f_weight: "normal",
    $dwku_top_xl: "42px",
    $dwku_top_l: "42px",
    $dwku_top_m: "42px",
    $dwku_top_s: "23px",
    
    //primary cta variables
    $cta_bg : "rgba(66, 20, 95, 1)",
    $cta_bor_rad : "0px",
    $cta_lineh : "26px",

    //WINK Variables
     $stand_alone_title_color : "rgba(44, 6, 55, 1)",
     $winks_sildertit_font:'RNHouseSansLight, sans-serif',

     /* WINKS xl screen variables */
    $winks_margtop_xl:"30px",
    $winks_display_xl:"block",
    $winks_sildertit_fs_xl:"52px",
    $winks_sildertit_lh_xl:"62px",
    $winks_sildertit_color:"rgb(68, 14, 94)",
    $winks_margtop_item_xl:"40px",
    $winks_slideritem_space:"40px 26px 59px",
    $winks_slideritem_xl_pt:"40px",
    $winks_slideritem_xl_pl:"26px",
    $winks_slideritem_xl_pb:"59px",
    $winks_slideritem_xl_pr:"26px",
    $winks_title_top_xl:"30px",
    $winks_title_top_xl:"30px",
    $winks_title_fs_xl:"30px",
    $winks_title_lh_xl:"38px",
    $winks_text_fs_xl:"18px",
    $winks_text_lh_xl:"26px",
    $winks_textcolor:"rgb(51, 51, 51)",
    $winks_content_hgt_xl:"188px",
    $winks_slider_col_hgt_xl:"539px",
     /* WINKS large screen variables */
    $winks_margtop_l:"30px",
    $winks_sildertit_fs_l:"42px",
    $winks_sildertit_lh_l:"54px",
    $winks_margtop_item_l:"30px",
    $winks_slideritem_space_l:"30px 20px 40px",
    $winks_slideritem_l_pt:"30px",
    $winks_slideritem_l_pl:"20px",
    $winks_slideritem_l_pb:"40px",
    $winks_slideritem_l_pr:"20px",
    $winks_title_top_l:"30px",
    $winks_title_fs_l:"26px",
    $winks_title_lh_l:"34px",
    $winks_content_hgt_l:"236px",
    $winks_slider_col_hgt_l:"518px",
    $winks_border_color:"rgba(29, 123, 138, 1)",
    $winks_border_style:"solid",
    $winks_border_width:"1px",
    /* WINKS medium screen variables */
    $winks_margtop_m:"30px",
    $winks_sildertit_fs_m:"34px",
    $winks_sildertit_lh_m:"44px",
    $winks_margtop_item_m:"23px",
    $winks_slideritem_space_m:"23px 0px 0px",
    $winks_slideritem_m_pt:"23px",
    $winks_slideritem_m_pl:"0px",
    $winks_slideritem_m_pb:"0px",
    $winks_title_max_h_xl:"76px",
    $winks_title_max_h_l:"68px",
    $winks_title_max_h_m:"64px",
    $winks_title_max_h_s:"68px",
    $winks_slideritem_m_pr:"0px",
    $winks_title_top_m:"40px",
    $winks_title_fs_m:"24px",
    $winks_title_lh_m:"32px",
    $winks_content_hgt_m:"224px",
    $winks_slider_col_hgt_m:"582px",
    /* WINKS small screen variables */
    $winks_margtop_s:"20px",
    $winks_sildertit_fs_s:"34px",
    $winks_sildertit_lh_s:"44px",
    $winks_margtop_item_s:"8px",
    $winks_slideritem_space_s:"20px 0px 0px",
    $winks_slideritem_s_pt:"20px",
    $winks_slideritem_s_pl:"0px",
    $winks_slideritem_s_pb:"0px",
    $winks_slideritem_s_pr:"0px",
    $winks_title_top_s:"30px",
    $winks_title_fs_s:"34px",
    $winks_title_lh_s:"44px",
    $winks_content_hgt_s:"218px",
    $winks_slider_col_hgt_s:"546px",
    $winks_arrows_bg:"rgb(68, 14, 94)",

     // WINKS Image Properties
    natwest_image_width:"222px",
    natwest_image_padding:"0px",
    natwest_image_height:"222px",
     //l
    natwest_image_width_l:"182px",
    natwest_image_height_l:"182px",
    natwest_image_width_m:"270px",
    natwest_image_height_m:"270px",
    natwest_image_width_s:"217px",
    natwest_image_height_s:"217px",
    natwest_image_theight_xl:"220px",
    natwest_image_theight_l:"268px",
    natwest_image_theight_m:"206px",
    natwest_image_theight_s:"220px",
    natwest_image_padding_top_m:"40px",
    natwest_image_padding_bottom_m:"20px",
    natwest_image_padding_top_s:"50px",
    natwest_image_padding_bottom_s:"22px",

    //dwku toggle variables
    $tog_bor_rad : "0px",
    $bor_t_l_rad : "0px",
    $bor_b_l_rad : "0px",
    $bor_t_r_rad : "100px",
    $bor_b_r_rad : "100px",
    $tog_bor_rad_right : "0px",

    //why us shelf variables
    $whyus_bg_cocor: "rgb(44, 6, 55)",
    $whyus_twill_height: "10px",
    $whyus_margin_bottom: "20px",
    $whyush3title: "rgb(149, 107, 90)",
    
    //hero-shelf styles
    $hero_wrap_height_xl:"480px",
    $hero_wrap_height_l:"422px",
    $hero_wrap_height_m:"416px",
   $hero_wrap_height_s:"457px",
   $hero_block_bgColor:"rgb(44, 6, 55)",
  $heroTitleonePaddingTop : '30px',
    $heroTitleonePaddingBtm : '6px',
    $heroTitleonePaddingMdTop : '23px',
    $heroTitleonePaddingMdBtm : '4px',
    $heroTitleonePaddingSmTop : '19px',
    $heroTitleonePaddingSmBtm : '2px',
    $heroTitleonePaddingXsTop : '20px',
    $heroTitleonePaddingXsBtm : '0px',
    $heroshelfnwBgClr : "rgb(44, 6, 55)",
    illbgcolorHero : "rgb(44, 6, 55)",
   $heroPaddingxl:"20px 42px 40px",
   $heroPaddingl:"22px 55px 40px 40px",
    $heroPaddingm:"20px 30px 30px 29px",
    $heroPaddings:"20px 20px 30px 20px",
    $heroProdBgClr: "rgb(224, 220, 220)",


   //standalone styles
   $font_family_shelf:"RNHouseSansLight, sans-serif",
   $font_weight_shelf:"normal",
   $standalone_title_mt : "7px",
   $standalone_title_mb : "17px",
   $standalone_icon_yellow : "rgb(251, 186, 32)", //yellow icon
   $standalone_icon_pink : "rgb(206, 59, 87)",
   $standalone_icon_width :  "36px",
   $standalone_icon_width_m : "31px",
   $standalone_icon_height :  "35px",
   $standalone_icon_height_m : "30px",

   //At a Glance shelf
   $ataglance_title_color : "rgba(66, 20, 95, 1)",
   $ataglance_title_lh : "40px",
   $ataglance_title_fs : "30px",
   $winks_textcolor : "rgb(51, 51, 51)",

   //Get help shelf properties
   $furtherAsstPaddingTop : '77px',
   $furtherAsstPaddingBtm : '104px',
   $furtherAsstPaddingMDBtm : '104px',
   $furtherAsstPaddingSMTop : '77px',
   $furtherAsstPaddingSMBtm : '93px',
   $furtherAsstPaddingXSTop : '70px',
   $furtherAsstPaddingXSBtm : '70px',
   $SearchWrapTop : '48px',
   $SearchWrapBottom : '34px',
   $SearchWrapSmTop : '48px',
   $SearchWrapSmBottom : '0px',
   $SearchWrapXsTop : '32px',
   $SearchWrapXsBottom : '0px',
   $searchBorderColor : 'rgba(0, 159, 172, 1)',
   $searchBorderBtmColor : 'rgba(0, 159, 172, 1)',
   $searchBorderWidth : '2px',
   $searchBorderBtmWidth : '2px',
   $searchBorderStyle : 'solid',
   $searchBorderBtmStyle : 'solid',
   $searchRight : '20px',
   $searchTop: '18px',
   $searchSMRight : '12px',
   $searchSMTop : '20px',
   $searchPsuedoFont: '33px',
   $toolMargin : '50px',
   $toolSMMargin : '50px',
   $toolXSMargin : '45px',
   $toolImgSize : '42px',
   $toolImgMDSize : '38px',
   $toolTitleTopMargin: '2px',
   $toolTitleBtmMargin : '1px',
   $toolTitleTopSMMargin : '2px',
   $toolTitleBtmSMMargin : '0px',
 //Contexual links styles
   $context_link_mt_xl : "78px",
   $context_link_mb_xl : "60px",
   $context_link_mt_l   : "67px",
   $context_link_mb_l   : "44px",
   $context_link_mt_m   : "65px",
   $context_link_mb_m   : "55px",
   $context_link_mt_s   : "67px",
   $context_link_mb_s   : "48px",
   $context_menu_link_fs : "18px",
   $context_menu_link_lh : "32px",
   
   //contexual links divider styles
   $context_divider_mt_xl : "32px",
   $context_divider_mb_xl : "4px",
   $context_divider_mt_l : "38px",
   $context_divider_mb_l : "14px",
   $context_divider_mt_m : "26px",
   $context_divider_mb_m : "14px",
   $context_divider_border_color :"1px solid rgb(255, 255, 255)",

   $anchorTestdecoration: 'none solid rgb(66, 20, 95)',
   $anchorBG : 'rgb(66, 20, 95) none repeat scroll 0% 0% / auto padding-box border-box',

   /*Global notifications variables*/
   $notiI589mageSize : "110px",
   $notiImageMDSize : "100px",
   $notificationBg : "rgba(29, 123, 138, 1)",
   $notiMDPadding : "52px",
   $notiMDPaddingBtm : "52px",
   $notiPaddingLeft : "0px",

   $notiMDPaddingLeft : "0px",

   $notiLPaddingLeft : "0px",
   $notiMDPaddingLeft : "0px",
   $CTAMarginBtm : "0px",
   $notiTitleWidth : "471.625px",
   $notiTitleMDWidth : "449.625px",
   $notiTitleSMWidth : "403.188px",
   $notiTextWidth : "668.984px",
   $notiTextMDWidth : "528.984px",
   $notiTextSMWidth : "525px",
   $verticalLineDisp : 'block',
   $notiImageXLMargin: "0px",
   $notiTransform : "matrix(1, 0, 0, 1, 0, -55)",
   $notiMDTransform : "matrix(1, 0, 0, 1, 0, -50)",


   // credit card variables
   $primary_1 : 'rgb(44, 6, 55)',
   $primary : 'rgba(44, 6, 55, 1)',
   $slider_handle_height_xl : "48px",
   $slider_handle_height_l : "47px",
   $slider_handle_height_sm :"48px",
   $slider_handle_height_xs : "42px",

   // Product details
   $font_color_differ : 'rgba(44, 6, 55, 1)',
   $color_whitesmoke : 'rgb(245, 245, 245)',
   $font_weight_product : '400',
   $font_family_product : 'RNHouseSansLight, sans-serif',

   $myDemopTopBttm:"10px",
   $myDemoplftRyt:"20px",

   // For global search XL & L
   $searhBoxWidth_xl:"204px",
   $gsMarginTop : "11px",
   $gsMarginBot: "9px",
   $gsHeight : "39px",
   $gsInputWid : "162px",
   $gsInpPadTop: "6px",
   $gsInpPadBot: "7px",
   $gsInpPadLft:"8px",
   $gsImgWid:"20px",
   $gsImgHgt:"20px",
   $gsImgMarTop:"8px",
   $gsImgMarBot:"8px",
   $gsImgMarRgt:"8px",
   $gsImgMarLft:"10px",
   $gsBorColr:"rgba(0, 159, 172, 1)",
   $gsBorColrBtm:"rgba(0, 159, 172, 1)",
   $gsBorWid:"2px",
   $gsBorWidBot:"2px",
   $gsBorStyle:"solid",
   $gsBorStyleBtm:"solid",
   $gsInptFontSize:"14px",
   $gsInptLineHgt:"22px",
   $gsInptTxtColr:"rgba(95, 95, 95, 1)",
   $gsFontFamily:"RNHouseSansRegular, sans-serif",

  // For global search M & S
   $searhBoxWidth_m:"250px",
   $gsMarginTop_m : "6px",
   $gsMarginBot_m: "5px",
   $gsMarginLft_m : "5px",
   $gsMarginRgt_m: "5px",
   $gsHeight_m : "36px",
   $gsInputWid_m : "197px",
   $gsInpPadTop_m: "5px",
   $gsInpPadBot_m:"5px",
   $gsInpPadlft_m:"8px",
   $gsImgMarTop_m:"6px",
   $gsImgMarBot_m:"6px",
   $gsImgMarLft_m:"10px",
   $gsImgMarRgt_m:"8px",

    //product Listing 
   $productIncomeClr: "rgba(149, 107, 90, 1)",
   $productH3font_26: "26px",
   $productH3lh: "34px",
   $productButton: "rgba(29, 123, 138, 1)",
   $productH3Color : "rgba(44, 6, 55, 1)",
   $productImg_s : "179px",
   $productImg_m : "147px",
   $h4Cust_font_size_xl:"22px",
   $h4Cust_line_height_xl:"30px",
   $h4Cust_font_size_l:"22px",
   $h4Cust_line_height_l:"30px",
   $h4Cust_font_size_m:"18px",
   $h4Cust_line_height_m:"26px",
   $h4Cust_font_size_s:"18px",
   $h4Cust_line_height_s:"26px",

   $h3Cust_font_size_xl:"26px",
   $h3Cust_line_height_xl:"34px",
   $h3Cust_font_size_l:"24px",
   $h3Cust_line_height_l:"32px",
   $h3Cust_font_size_ms:"24px",
   $h3Cust_line_height_ms:"32px",

   $productTitleH2_m : '23px',
   $productTitleH2_xs : '22px',
   
   $productShelf_pt_xl : '27px',
   $productShelf_pt_m : '27px',
   $productShelf_pb_m : '22px',
   $productShelf_pt_xs : '33px',
   $productShelf_pb_xs : '42px',
   $productSelfImg_w : '31px',
   $productSelfImg_h : '30px',
   $productSelfLiSquare : '24px',
   $font_family_bold_2:"RNHouseSansRegular, sans-serif",
   $productSelfCtaTop_xl: '25px',
   $productSelfCtaTop_m: '20px',
   $productMultiImg_s: '179px',
   //Article shelf
   $bg_color : "rgba(206, 59, 87, 1)",
   //footer-component-variables
   $footer_bg_color : "rgba(44, 6, 55, 1)",
   $footer_bg_image : "none",
   //product-detail shelf
   $productDetail_tabBgColor : "rgba(229, 216, 211, 1)",

   //single article shelf 
   $shelf_Padding_Bottom: "20px",

   //download shelf
   $padding_top: "40px",
   $padding_bottom: "30px",
   $padding_topM: "35px",
   $padding_bottomM: "30px",
   $padding_topS: "30px",
   $padding_bottomS: "50px",
   $padding_topXS: "30px",
   $padding_bottomXS: "50px",
   $download_nopadding: "0px 0px 2px",

   $titleWrapper_margin_top_lg: "14px",
   $titleWrapper_margin_top_xs: "12px",

   $link_margin_bottom: "18px",
   
   //toggle shelf
   $bgColor : "rgba(111, 44, 145, 1)",
   $border_top_left_radius: "0px",
   $border_top_right_radius: "0px",
   $border_bottom_left_radius: "0px",
   $border_bottom_right_radius: "0px",

   
   $EvenTogg_border_top_left_radius: "0px",
   $EvenTogg_border_top_right_radius: "0px",
   $EvenTogg_border_bottom_left_radius: "0px",
   $EvenTogg_border_bottom_right_radius: "0px", 

   $cta_padding_top: "15px",
   $cta_padding_right: "20px",
   $cta_padding_bottom: "15px",
   $cta_padding_left: "20px",

   //pre-apply business 
   $shelf_bg_color: "rgba(111, 44, 145, 1)",
   $singleArticle_padding_bottom: "20px",

   //header Section
   $header_bg_color : "rgba(66, 20, 95, 1)",
   $L2text_color  : "rgba(12, 127, 136, 1)",

   //campaign promo
  $cp_primarycta_top_margin_xl: "35px",
  $cp_cta_padding_top: "15px",
  $cp_cta_padding_right: "20px",
  $cp_cta_padding_bottom: "15px",
  $cp_cta_padding_left: "20px",
  $cp_font_color : "rgb(149, 107, 90)",

   //breadcrumb links
   $linkcolor : "rgb(29, 123, 138)",
   $linkborderbottom : "1px solid rgb(29, 123, 138)",
   $currentlink : "rgba(44, 6, 55, 1)",

   //table shelf
   $heading_max_height: "64px",
   $image_margin_right: "13px",
   $table_shelf_font_color : "rgba(149, 107, 90, 1)",
  $table_shelf_dd_font_color : "rgb(44, 6, 55)",
  $text_padding_left: "35px",
  $text_background_size:"22px 23px",
  $table_shelf_textcolor:"rgb(51, 51, 51)",

  //needbased panel
  $taskBased_bgColor : "linear-gradient(to right, rgb(70, 49, 98), rgb(29, 20, 48))",
  $taskpanel_bgcolor : "rgb(0, 0, 0)",
  $taskpanel_pad_bottom : "70px",
  $taskpanel_pad_bottom_med : "50px",
  $titleTextFontWeight : "normal",

  $img_margin_left_right_lg : "17.5px",
  $img_width_height_lg : "139px",
  $img_margin_left_right_md : "13.5px",
  $img_width_height_md : "107px",
  $img_margin_left_right_sm : "16px",
  $img_width_height_sm : "78px",

  $cta_padding_top : "20px",

  $searchWrap_padding_bottom : "70px",
  $search_bg_color : "linear-gradient(to right, rgb(70, 49, 98), rgb(29, 20, 48))",
  $searchWrap_padding_bottom_sm : "50px",
  $searchWrap_padding_bottom_xs : "50px",

  $searchLabel_float_lg : "left",
  $searchLabel_margin_rt_lg : "20px",
  $searchLabel_margin_bottom_sm : "15px",
  $searchLabel_padding_top_lg : "0px",
  $searchLabel_padding_top_md : "0px",
  $searchLabel_textalign_sm : "center",
  $searchLabel_padding_top_sm : "0px",
  $searchLabel_padding_top_xs : "0px",
  $searchLabel_height_lg : "80px",
  $searchLabel_height_md : "72px",
  $searchLabel_height_sm : "32px",
  $searchLabel_height_xs : "32px",
  $searchFontWeight : "bold",

  $searchinp_border_top_style: "solid",
  $searchinp_border_left_style: "solid",
  $searchinp_border_right_style: "solid",
  $searchinp_border_bottom_style:"solid",            
  $searchinp_border_top_width: "2px",
  $searchinp_border_left_width: "2px",
  $searchinp_border_right_width: "2px",
  $searchinp_border_bottom_width:"2px", 
  $searchinp_border_top_color: "rgb(0, 159, 172)",
  $searchinp_border_left_color: "rgb(0, 159, 172)",
  $searchinp_border_right_color: "rgb(0, 159, 172)",
  $searchinp_border_bottom_color:"rgb(0, 159, 172)",  
  $searchinp_background_color: "rgb(255, 255, 255)",
  $searchinp_padding_top: "17px",
  $searchinp_padding_right: "17px",
  $searchinp_padding_bottom: "17px",
  $searchinp_padding_left: "20px",
  $searchinp_padding_top_sm: "17px",
  $searchinp_padding_right_sm: "17px",
  $searchinp_padding_bottom_sm: "17px",
  $searchinp_padding_left_sm: "20px",
  $searchinp_padding_top_xs: "17px",
  $searchinp_padding_bottom_xs: "17px",

  //404-500 Error Page
  $errorPage_img_width: "200px",
  $errorPage_img_height: "200px",
  $errorPage_title_color: "rgb(66, 20, 95)",
  $errorPage_title_family: "RNHouseSansRegular, sans-serif",
  $errorPage_text_color: "rgb(51, 51, 51)",
  
  $searchText_padding_top: "21px",
  $searchText_padding_right: "17px",
  $searchText_padding_bottom: "20px",
  $searchText_padding_left: "32px",

  $searchText_padding_top_med: "17px",
  $searchText_padding_right_med: "17px",
  $searchText_padding_bottom_med: "16px",
  $searchText_padding_left_med: "22px",
  $errorPage_searchText_color : "rgb(95, 95, 95)",
  //actionable-content variables
  $act_cont_grey_color_on_white_bg :"rgb(245, 245, 245)",
  $act_cont_grey_color_on_Brand_bg : "rgb(44, 6, 55)",
  $fill_color_on_brand_bg : "rgb(255, 255, 255)",
  $fill_color_on_white_bg : "rgb(44, 6, 55)",
  $actContTitleColoronWhiteBg : "rgb(44, 6, 55)",
  $actContTitleColoronBrandBg : "rgb(255, 255, 255)",
  $actContTextColoronWhiteBg : "rgb(51, 51, 51)",
  $actContCTAColor : "rgb(29, 123, 138)",
  $regular_font_family: 'RNHouseSansRegular, sans-serif',
  $light_font_family: 'RNHouseSansLight, sans-serif',
  $bold_font_family: 'RNHouseSansBold, sans-serif',
  $primaryCTAFontFamily : 'RNHouseSansRegular, sans-serif',

  //incident Notification
   $incident_bg_color : "rgb(29, 123, 138)",
   $incident_ptop : "52px",
   $incident_pbottom : "32px",
   $incident_title_family : "RNHouseSansLight, sans-serif",

   //Completion Prompt shelf
    $completionprompt_image_size : "110px",
    $completionprompt_image_size_l : "100px",
    $completionprompt_content_pl : "0px",
    $completionprompt_content_pl_l :"0px",
    $completionprompt_rte_color : "rgb(51, 51, 51)",
    $completionprompt_FontFamily : "RNHouseSansLight, sans-serif",
    $primCta_background : "rgb(29, 123, 138)",
    $verticalLine_background : "rgb(216, 216, 216)",
    $completionprompt_rteFontFamily : "RNHouseSansLight, sans-serif",
    $completion_primCTA_pb : "15px",
    $completion_primCTA_pt : "15px",
    $completion_secCTA_margin : "15px",
    $completion_secCTA_color : "rgb(29, 123, 138)",

};

module.exports = {
    props: natwest
}
