var natwest = {
  $primary_1 : 'rgb(66, 20, 95)',
  $primary_2 : "rgb(255, 255, 255)",
  $font_family_text: "RNHouseSansRegular, sans-serif",
  $font_family_bold_2:"RNHouseSansBold, sans-serif",
  $font_family_title:"RNHouseSansRegular, sans-serif",
//needbased panel
  $taskBased_bgColor : "linear-gradient(to right, rgb(70, 49, 98), rgb(29, 20, 48))",
  $taskpanel_bgcolor : "rgb(0, 0, 0)",
  $taskpanel_pad_bottom : "70px",
  $taskpanel_pad_bottom_med : "50px",
  $titleTextFontWeight : "normal",

  $img_margin_left_right_lg : "17.5px",
  $img_width_height_lg : "139px",
  $img_margin_left_right_md : "13.5px",
  $img_width_height_md : "107px",
  $img_margin_left_right_sm : "16px",
  $img_width_height_sm : "78px",

  $cta_padding_top : "20px",
  $marginTopAcc : "4px",
  $padding_topM: "40px",
   $padding_bottomM: "30px",
   $padding_topS: "40px",
   $padding_bottomS: "30px",
   $padding_topXS: "40px",
   $padding_bottomXS: "30px",

  $searchWrap_padding_bottom : "70px",
  $search_bg_color : "linear-gradient(to right, rgb(70, 49, 98), rgb(29, 20, 48))",
  $searchWrap_padding_bottom_sm : "50px",
  $searchWrap_padding_bottom_xs : "50px",

  $searchLabel_float_lg : "left",
  $searchLabel_margin_rt_lg : "20px",
  $searchLabel_margin_bottom_sm : "15px",
  $searchLabel_padding_top_lg : "0px",
  $searchLabel_padding_top_md : "0px",
  $searchLabel_textalign_sm : "center",
  $searchLabel_padding_top_sm : "0px",
  $searchLabel_padding_top_xs : "0px",
  $searchLabel_height_lg : "80px",
  $searchLabel_height_md : "72px",
  $searchLabel_height_sm : "32px",
  $searchLabel_height_xs : "32px",
  $searchFontWeight : "bold",

  $searchinp_border_top_style: "solid",
  $searchinp_border_left_style: "solid",
  $searchinp_border_right_style: "solid",
  $searchinp_border_bottom_style:"solid",            
  $searchinp_border_top_width: "2px",
  $searchinp_border_left_width: "2px",
  $searchinp_border_right_width: "2px",
  $searchinp_border_bottom_width:"2px", 
  $searchinp_border_top_color: "rgb(0, 159, 172)",
  $searchinp_border_left_color: "rgb(0, 159, 172)",
  $searchinp_border_right_color: "rgb(0, 159, 172)",
  $searchinp_border_bottom_color:"rgb(0, 159, 172)",  
  $searchinp_background_color: "rgb(255, 255, 255)",
  $searchinp_padding_top: "17px",
  $searchinp_padding_right: "17px",
  $searchinp_padding_bottom: "17px",
  $searchinp_padding_left: "20px",
  $searchinp_padding_top_sm: "17px",
  $searchinp_padding_right_sm: "17px",
  $searchinp_padding_bottom_sm: "17px",
  $searchinp_padding_left_sm: "20px",
  $searchinp_padding_top_xs: "17px",
  $searchinp_padding_bottom_xs: "17px",

  //404-500 Error Page
  $errorPage_img_width: "200px",
  $errorPage_img_height: "200px",
  $errorPage_title_color: "rgb(66, 20, 95)",
  $errorPage_title_family: "RNHouseSansRegular, sans-serif",
  $errorPage_text_color: "rgb(51, 51, 51)",
  
  $searchText_padding_top: "19px",
  $searchText_padding_right: "17px",
  $searchText_padding_bottom: "19px",
  $searchText_padding_left: "32px",

  $searchText_padding_top_med: "17px",
  $searchText_padding_right_med: "17px",
  $searchText_padding_bottom_med: "17px",
  $searchText_padding_left_med: "22px",
  $errorPage_searchText_color : "rgb(95, 95, 95)",

  //incident Notification
   $incident_bg_color : "rgb(29, 123, 138)",
   $incident_ptop : "52px",
   $incident_pbottom : "32px",
   $incident_title_family : "RNHouseSansLight, sans-serif",

   //Completion Prompt shelf
    $completionprompt_image_size : "110px",
    $completionprompt_image_size_l : "100px",
    $completionprompt_content_pl : "0px",
    $completionprompt_content_pl_l :"0px",
    $completionprompt_rte_color : "rgb(51, 51, 51)",
    $completionprompt_FontFamily : "RNHouseSansRegular, sans-serif",
    $primCta_background : "rgb(29, 123, 138)",
    $verticalLine_background : "rgb(216, 216, 216)",
    $color_whitesmoke : "rgb(245, 245, 245)",
    $completionprompt_rteFontFamily : "RNHouseSansRegular, sans-serif",
     $completion_primCTA_pb : "15px",
    $completion_primCTA_pt : "15px",
    $completion_secCTA_margin : "15px",
    $completion_secCTA_color : "rgb(29, 123, 138)",

    //campaign promo
  $cp_primarycta_top_margin_xl: "35px",
  $cp_cta_padding_top: "15px",
  $cp_cta_padding_right: "20px",
  $cp_cta_padding_bottom: "15px",
  $cp_cta_padding_left: "20px",
  $cp_font_color : "rgba(66, 20, 95, 1)",

    //table accordion
    $linkcolor : "rgb(29, 123, 138)",
    $font_family_regular:"RNHouseSansRegular, sans-serif",
    $accContmPadding:"35px",
    $font_color_regular:"rgb(66, 20, 95)",
    $font_family_bold:"RNHouseSansBold, sans-serif",
    $acc_contText_color: "rgb(50, 50, 50)",

    //message only header variables
    $msgOnly_headerImg_height : "20px",
    $msgOnly_headerImg_width : "102px",

    //why us shelf variables
    $whyus_bg_cocor: "rgb(66, 20, 95)",
    $whyus_twill_height: "10px",
    $whyus_margin_bottom: "30px",
    $whyush3title: "rgb(66, 20, 95)",

    //Get help shelf properties
   $furtherAsstPaddingTop : '77px',
   $furtherAsstPaddingBtm : '104px',
   $furtherAsstPaddingMDBtm : '104px',
   $furtherAsstPaddingSMTop : '77px',
   $furtherAsstPaddingSMBtm : '93px',
   $furtherAsstPaddingXSTop : '70px',
   $furtherAsstPaddingXSBtm : '70px',
   $SearchWrapTop : '48px',
   $SearchWrapBottom : '34px',
   $SearchWrapSmTop : '48px',
   $SearchWrapSmBottom : '0px',
   $SearchWrapXsTop : '32px',
   $SearchWrapXsBottom : '0px',
   $searchBorderColor : 'rgba(0, 159, 172, 1)',
   $searchBorderBtmColor : 'rgba(0, 159, 172, 1)',
   $searchBorderWidth : '2px',
   $searchBorderBtmWidth : '2px',
   $searchBorderStyle : 'solid',
   $searchBorderBtmStyle : 'solid',
   $searchRight : '20px',
   $searchTop: '18px',
   $searchSMRight : '12px',
   $searchSMTop : '20px',
   $searchPsuedoFont: '33px',
   $toolMargin : '50px',
   $toolSMMargin : '50px',
   $toolXSMargin : '45px',
   $toolImgSize : '42px',
   $toolImgMDSize : '38px',
   $toolTitleTopMargin: '2px',
   $toolTitleBtmMargin : '1px',
   $toolTitleTopSMMargin : '2px',
   $toolTitleBtmSMMargin : '0px',
};

module.exports = {
    props: natwest
}