var natwest = {
    $primary_2 : "rgb(255, 255, 255)",
    $stand_alone_title_color : "rgba(66, 20, 95, 1)",
    $font_family_bold:'RNHouseSansBold, sans-serif',
    $font_family_regular: 'RNHouseSansRegular, sans-serif',
    $winks_sildertit_font:'RNHouseSansRegular, sans-serif',
    $font_family_light:"RNHouseSansLight, sans-serif",
    $cookie_bgColor: "rgb(44, 6, 55)",
    $font_family_text: "RNHouseSansRegular, sans-serif",
    $font_family_cta: "RNHouseSansRegular, sans-serif",
    $cookie_close_color:"rgb(255, 0, 0)",
    $whyush3title: "rgb(66, 20, 95)",
    $borderbottomcolor:"1px solid rgb(51, 51, 51)",
    $accContmPadding:"35px",
    /* WINKS xl screen variables */
    $winks_margtop_xl:"30px",
    $winks_display_xl:"block",
    $winks_sildertit_fs_xl:"52px",
    $winks_sildertit_lh_xl:"62px",
    $winks_sildertit_color:"rgb(68, 14, 94)",
    $winks_margtop_item_xl:"40px",
    $winks_slideritem_space:"40px 26px 59px",
    $winks_slideritem_xl_pt:"40px",
    $winks_slideritem_xl_pl:"26px",
    $winks_slideritem_xl_pb:"59px",
    $winks_slideritem_xl_pr:"26px",
    $winks_title_top_xl:"30px",
    $winks_title_top_xl:"30px",
    $winks_title_fs_xl:"30px",
    $winks_title_lh_xl:"38px",
    $winks_text_fs_xl:"18px",
    $winks_text_lh_xl:"26px",
    $winks_textcolor:"rgb(51, 51, 51)",
    $winks_content_hgt_xl:"188px",
    $winks_slider_col_hgt_xl:"539px",
     //Image Properties
    natwest_image_width:"222px",
    natwest_image_padding:"0px",
    natwest_image_height:"222px",
     //l
    natwest_image_width_l:"182px",
    natwest_image_height_l:"182px",
    natwest_image_width_m:"270px",
    natwest_image_height_m:"270px",
    natwest_image_width_s:"217px",
    natwest_image_height_s:"217px",
    
    natwest_image_theight_xl:"220px",
    natwest_image_theight_l:"268px",
    natwest_image_theight_m:"206px",
    natwest_image_theight_s:"220px",

    natwest_image_padding_top_m:"40px",
    natwest_image_padding_bottom_m:"20px",
    natwest_image_padding_top_s:"50px",
    natwest_image_padding_bottom_s:"22px",
    /* WINKS large screen variables */
    $winks_margtop_l:"30px",
    $winks_sildertit_fs_l:"42px",
    $winks_sildertit_lh_l:"54px",
    $winks_margtop_item_l:"30px",
    $winks_slideritem_space_l:"30px 20px 40px",
    $winks_slideritem_l_pt:"30px",
    $winks_slideritem_l_pl:"20px",
    $winks_slideritem_l_pb:"40px",
    $winks_slideritem_l_pr:"20px",
    $winks_title_top_l:"30px",
    $winks_title_fs_l:"26px",
    $winks_title_lh_l:"34px",
    $winks_content_hgt_l:"236px",
    $winks_slider_col_hgt_l:"518px",
    $winks_border_color:"rgba(29, 123, 138, 1)",
    $winks_border_style:"solid",
    $winks_border_width:"1px",
    /* WINKS medium screen variables */
    $winks_margtop_m:"30px",
    $winks_sildertit_fs_m:"34px",
    $winks_sildertit_lh_m:"44px",
    $winks_margtop_item_m:"23px",
    $winks_slideritem_space_m:"23px 0px 0px",
    $winks_slideritem_m_pt:"23px",
    $winks_slideritem_m_pl:"0px",
    $winks_slideritem_m_pb:"0px",
    $winks_title_max_h_xl:"76px",
    $winks_title_max_h_l:"68px",
    $winks_title_max_h_m:"32px",
    $winks_title_max_h_s:"68px",
    $winks_slideritem_m_pr:"0px",
    $winks_title_top_m:"40px",
    $winks_title_fs_m:"24px",
    $winks_title_lh_m:"32px",
    $winks_content_hgt_m:"224px",
    $winks_slider_col_hgt_m:"582px",
    /* WINKS small screen variables */
    $winks_margtop_s:"20px",
    $winks_sildertit_fs_s:"34px",
    $winks_sildertit_lh_s:"44px",
    $winks_margtop_item_s:"8px",
    $winks_slideritem_space_s:"20px 0px 0px",
    $winks_slideritem_s_pt:"20px",
    $winks_slideritem_s_pl:"0px",
    $winks_slideritem_s_pb:"0px",
    $winks_slideritem_s_pr:"0px",
    $winks_title_top_s:"30px",
    $winks_title_fs_s:"34px",
    $winks_title_lh_s:"44px",
    $winks_content_hgt_s:"218px",
    $winks_slider_col_hgt_s:"546px",
    $winks_arrows_bg:"rgb(68, 14, 94)",
    //XL Styles
    $h1_font_size_xl:"52px",
    $h1_line_height_xl:"64px",
    $h2_cust_font_size_xl:"40px",
    $h2_cust_line_height_xl:"50px",
    $h3_font_size_xl:"30px",
    $h3_line_height_xl:"40px",
    $h4_font_size_xl:"22px",
    $h4_line_height_xl:"32px",

    //L Styles
    $h1_font_size_l:"42px",
    $h1_line_height_l:"54px",
    $h2_cust_font_size_l:"38px",
    $h2_cust_line_height_l:"48px",
    $h3_font_size_l:"26px",
    $h3_line_height_l:"36px",
    $h3_cust_font_size_l:"24px",
    $h3_cust_line_height_l:"32px",    

    //M Styles
    $h1_font_size_m:"34px",
    $h1_line_height_m:"44px",
    $h2_cust_font_size_m:"28px",
    $h2_cust_line_height_m:"38px",
    $h3_font_size_m:"24px",
    $h3_line_height_m:"32px",

    //S Styles
    $h1_font_size_s:"34px",
    $h1_line_height_s:"44px",
    $h2_cust_font_size_s:"34px",
    $h2_cust_line_height_s:"44px",
    $h3_font_size_s:"24px",
    $h3_line_height_s:"32px",
    //hero-shelf styles
    $hero_wrap_height_xl:"480px",
    $hero_wrap_height_l:"422px",
    $hero_wrap_height_m:"416px",
   $hero_wrap_height_s:"501px",
   $hero_block_bgColor:"rgba(251, 186, 32, 1)",
   $heroTitleonePaddingTop : '30px',
    $heroTitleonePaddingBtm : '6px',
    $heroTitleonePaddingMdTop : '23px',
    $heroTitleonePaddingMdBtm : '4px',
    $heroTitleonePaddingSmTop : '19px',
    $heroTitleonePaddingSmBtm : '2px',
    $heroTitleonePaddingXsTop : '20px',
    $heroTitleonePaddingXsBtm : '0px',

    //breadcrumb links
   $linkcolor : "rgba(29, 123, 138, 1)",
   $linkborderbottom : "1px solid rgb(29, 123, 138)",
   $currentlink : "rgba(44, 6, 55, 1)",

   //productListing backgrounds
   $background_1: "linear-gradient(to right, rgb(70, 49, 98), rgb(29, 20, 48))",
   $background_2: "linear-gradient(to right, rgb(70, 49, 98), rgb(29, 20, 48))",
   $background_3: "linear-gradient(to right, rgb(70, 49, 98), rgb(29, 20, 48))",
   $background_4: "linear-gradient(to right, rgb(70, 49, 98), rgb(29, 20, 48))",

   //single listing
   $background_single: "linear-gradient(to right, rgb(70, 49, 98), rgb(29, 20, 48))",

   //CMA backgrounds
   $background_eligibility: "linear-gradient(to right, rgb(70, 49, 98), rgb(29, 20, 48))",
   $background_indicative: "linear-gradient(to right, rgb(73, 55, 102), rgb(36, 25, 58))",

   //needbased panel
  $taskBased_bgColor : "linear-gradient(to right, rgb(70, 49, 98), rgb(29, 20, 48))",
  $taskpanel_bgcolor : "rgb(0, 0, 0)",
  $taskpanel_pad_bottom : "70px",
  $taskpanel_pad_bottom_med : "50px",
  $titleTextFontWeight : "400",

  $img_margin_left_right_lg : "17.5px",
  $img_width_height_lg : "139px",
  $img_margin_left_right_md : "13.5px",
  $img_width_height_md : "107px",
  $img_margin_left_right_sm : "16px",
  $img_width_height_sm : "78px",

  $cta_padding_top : "20px",

  $searchWrap_padding_bottom : "70px",
  $search_bg_color : "linear-gradient(to right, rgb(70, 49, 98), rgb(29, 20, 48))",
  $searchWrap_padding_bottom_sm : "50px",
  $searchWrap_padding_bottom_xs : "50px",
  $searchLabel_float_lg : "left",
  $searchLabel_margin_rt_lg : "20px",
  $searchLabel_margin_bottom_sm : "15px",
  $searchLabel_padding_top_lg : "0px",
  $searchLabel_padding_top_md : "0px",
  $searchLabel_textalign_sm : "center",
  $searchLabel_padding_top_sm : "0px",
  $searchLabel_padding_top_xs : "0px",
  $searchLabel_height_lg : "80px",
  $searchLabel_height_md : "72px",
  $searchLabel_height_sm : "32px",
  $searchLabel_height_xs : "32px",
  $searchFontWeight : "700",
  $searchinp_border_top_style: "solid",
  $searchinp_border_left_style: "solid",
  $searchinp_border_right_style: "solid",
  $searchinp_border_bottom_style:"solid",            
  $searchinp_border_top_width: "2px",
  $searchinp_border_left_width: "2px",
  $searchinp_border_right_width: "2px",
  $searchinp_border_bottom_width:"2px",  
  $searchinp_border_top_color: "rgb(0, 159, 172)",
  $searchinp_border_left_color: "rgb(0, 159, 172)",
  $searchinp_border_right_color: "rgb(0, 159, 172)",
  $searchinp_border_bottom_color:"rgb(0, 159, 172)",
  $searchinp_background_color: "rgb(255, 255, 255)",
  $searchinp_padding_top: "17px",
  $searchinp_padding_right: "17px",
  $searchinp_padding_bottom: "17px",
  $searchinp_padding_left: "20px",
  $searchinp_padding_top_sm: "17px",
  $searchinp_padding_right_sm: "17px",
  $searchinp_padding_bottom_sm: "17px",
  $searchinp_padding_left_sm: "20px",
  $searchinp_padding_top_xs: "17px",
  $searchinp_padding_bottom_xs: "17px",

  //404-500 Error Page
  $errorPage_img_width: "200px",
  $errorPage_img_height: "200px",
  $errorPage_title_color: "rgb(66, 20, 95)",
  $errorPage_title_family: '"RNHouseSansRegular", sans-serif',
  $errorPage_text_color: "rgb(51, 51, 51)",
  
  $searchText_padding_top: "21px",
  $searchText_padding_right: "17px",
  $searchText_padding_bottom: "20px",
  $searchText_padding_left: "32px",

  $searchText_padding_top_med: "17px",
  $searchText_padding_right_med: "17px",
  $searchText_padding_bottom_med: "16px",
  $searchText_padding_left_med: "22px",
  $errorPage_searchText_color : "rgb(95, 95, 95)",
  $act_cont_grey_color_on_white_bg :"rgba(245, 245, 245, 1)"
};

module.exports = {
    props: natwest
}
