var rbs = {
    brand: "RBS",
    $primary_2 : "rgba(255, 255, 255, 1)",
    $stand_alone_title_color : "rgba(0, 45, 100, 1)",
    $font_family_bold:'"RNHouseSansBold",sans-serif',
    $font_family_regular:'RNHouseSansRegular, sans-serif',
    $winks_sildertit_font:'RNHouseSansBold, sans-serif',
    $font_family_light:"RNHouseSansLight, sans-serif",
    $font_family_text: "RNHouseSansRegular, sans-serif",
    $font_family_cta: "RNHouseSansBold, sans-serif",
    $cookie_close_color:"rgb(255, 0, 0)",
    $whyush3title: "rgb(0, 45, 100)",
    $accContmPadding:"55px",
    /* WINKS xl screen variables */
    $winks_margtop_xl:"35px",
    $winks_display_xl:"block",
    $winks_sildertit_fs_xl:"46px",
    $winks_sildertit_lh_xl:"58px",
    $winks_sildertit_color:"rgb(68, 14, 94)",
    $winks_margtop_item_xl:"39px",
    $winks_slideritem_space:"40px 26px 59px 26px",
    $winks_slideritem_xl_pt:"40px",
    $winks_slideritem_xl_pl:"26px",
    $winks_slideritem_xl_pb:"59px",
    $winks_slideritem_xl_pr:"26px",
    $winks_title_top_xl:"30px",
    $winks_title_fs_xl:"28px",
    $winks_title_lh_xl:"38px",
    $winks_text_fs_xl:"18px",
    $winks_text_lh_xl:"26px",
    $winks_textcolor:"rgba(51, 51, 51, 1)",
    $winks_content_hgt_xl:"188px",
    $winks_slider_col_hgt_xl:"539px",
     //Image Properties
    natwest_image_width:"222px",
    natwest_image_padding:"0px",
    natwest_image_height:"222px",
     //l
    $winks_title_max_h_xl:"76px",
    $winks_title_max_h_l:"70px",
    $winks_title_max_h_m:"31px",
    $winks_title_max_h_s:"62px",
    
    natwest_image_width_l:"182px",
    natwest_image_height_l:"182px",
    natwest_image_width_m:"270px",
    natwest_image_height_m:"270px",
    natwest_image_width_s:"217px",
    natwest_image_height_s:"217px",

    natwest_image_padding_top_m:"40px",
    natwest_image_padding_bottom_m:"20px",
    natwest_image_padding_top_s:"53px",
    natwest_image_padding_bottom_s:"22px",

    natwest_image_theight_xl:"218px",
    natwest_image_theight_l:"267px",
    natwest_image_theight_m:"206px",
    natwest_image_theight_s:"211px",    
    /* WINKS large screen variables */
    $winks_margtop_l:"30px",
    $winks_sildertit_fs_l:"40px",
    $winks_sildertit_lh_l:"56px",
    $winks_margtop_item_l:"29px",
    $winks_slideritem_space_l:"29px 20px 40px 20px",
    $winks_slideritem_l_pt:"29px",
    $winks_slideritem_l_pl:"20px",
    $winks_slideritem_l_pb:"40px",
    $winks_slideritem_l_pr:"20px",
    $winks_title_top_l:"30px",
    $winks_title_fs_l:"25px",
    $winks_title_lh_l:"35px",
    $winks_border_color:"rgba(30, 128, 143, 1)",
    $winks_border_style:"solid",
    $winks_border_width:"1px",
    $winks_content_hgt_l:"236px",
    $winks_slider_col_hgt_l:"518px",
    /* WINKS medium screen variables */
    $winks_margtop_m:"32px",
    $winks_sildertit_fs_m:"32px",
    $winks_sildertit_lh_m:"42px",
    $winks_margtop_item_m:"23px",
    $winks_slideritem_space_m:"23px 0px 0px 0px",
    $winks_slideritem_m_pt:"23px",
    $winks_slideritem_m_pl:"0px",
    $winks_slideritem_m_pb:"0px",
    $winks_slideritem_m_pr:"0px",
    $winks_title_top_m:"41px",
    $winks_title_fs_m:"23px",
    $winks_title_lh_m:"31px",
    $winks_content_hgt_m:"224px",
    $winks_slider_col_hgt_m:"582px",
    /* WINKS small screen variables */
    $winks_margtop_s:"22px",
    $winks_sildertit_fs_s:"32px",
    $winks_sildertit_lh_s:"42px",
    $winks_margtop_item_s:"10px",
    $winks_slideritem_space_s:"20px 0px 0px 0px",
    $winks_slideritem_s_pt:"20px",
    $winks_slideritem_s_pl:"0px",
    $winks_slideritem_s_pb:"0px",
    $winks_slideritem_s_pr:"0px",
    $winks_title_top_s:"30px",
    $winks_title_fs_s:"23px",
    $winks_title_lh_s:"31px",
    $winks_content_hgt_s:"218px",
    $winks_slider_col_hgt_s:"546px",
    $winks_arrows_bg:"rgba(0, 45, 100, 1)",
    //XL Styles
    $h1_font_size_xl:"46px",
    $h1_line_height_xl:"58px",
    $h2_cust_font_size_xl:"36px",
    $h2_cust_line_height_xl:"46px",
    $h3_font_size_xl:"28px",
    $h3_line_height_xl:"38px",
    $h4_font_size_xl:"20px",
    $h4_line_height_xl:"30px",

    //L Styles
    $h1_font_size_l:"40px",
    $h1_line_height_l:"52px",
    $h2_cust_font_size_l:"36px",
    $h2_cust_line_height_l:"46px",
    $h3_font_size_l:"25px",
    $h3_line_height_l:"35px",
    $h3_cust_font_size_l:"25px",
    $h3_cust_line_height_l:"35px",  

    //M Styles
    $h1_font_size_m:"32px",
    $h1_line_height_m:"42px",
    $h2_cust_font_size_m:"26px",
    $h2_cust_line_height_m:"36px",
    $h3_font_size_m:"23px",
    $h3_line_height_m:"31px",

    //S Styles
    $h1_font_size_s:"32px",
    $h1_line_height_s:"42px",
    $h2_cust_font_size_s:"34px",
    $h2_cust_line_height_s:"44px",
    $h3_font_size_s:"23px",
    $h3_line_height_s:"31px",
     //hero-shelf styles
    $hero_wrap_height_xl:"478px",
    $hero_wrap_height_l:"430px",
    $hero_wrap_height_m:"418px",
    $hero_wrap_height_s:"486px",
    $hero_block_bgColor:"rgba(0, 45, 100, 1)",
    $heroTitleonePaddingTop : '30px',
    $heroTitleonePaddingBtm : '6px',
    $heroTitleonePaddingMdTop : '23px',
    $heroTitleonePaddingMdBtm : '4px',
    $heroTitleonePaddingSmTop : '19px',
    $heroTitleonePaddingSmBtm : '2px',
    $heroTitleonePaddingXsTop : '20px',
    $heroTitleonePaddingXsBtm : '0px',

    //breadcrumb links
   $linkcolor : "rgba(30, 128, 143, 1)",
   $linkborderbottom : "1px solid rgb(30, 128, 143)",
   $currentlink : "rgba(40, 0, 32, 1)",

   //productListing backgrounds
   $background_1: "rgb(0, 45, 100)",
   $background_2: "rgb(0, 45, 100)",
   $background_3: "rgb(0, 45, 100)",
   $background_4: "rgb(0, 45, 100)",

   //single listing
   $background_single: "rgb(0, 45, 100)",

   //needbased panel
  $taskBased_bgColor : "rgb(245, 245, 245)",
  $taskpanel_bgcolor : "rgb(245, 245, 245)",
  $taskpanel_pad_bottom : "20px",
  $taskpanel_pad_bottom_med : "20px",
  $title2Background : "rgba(0, 45, 100, 0.76)",

  $img_margin_left_right_lg : "43px",
  $img_width_height_lg : "88px",
  $img_margin_left_right_md : "23px",
  $img_width_height_md : "88px",
  $img_margin_left_right_sm : "11px",
  $img_width_height_sm : "88px",

  $cta_padding_top : "10px",

  $searchWrap_padding_bottom : "35px",
  $search_bg_color : "rgb(245, 245, 245)",
  $searchWrap_padding_bottom_sm : "30px",
  $searchWrap_padding_bottom_xs : "20px",

  $searchLabel_float_lg : "none",
  $searchLabel_margin_rt_lg : "0px",
  $searchLabel_margin_bottom_sm : "0px",
  $searchLabel_padding_top_lg : "15px",
  $searchLabel_padding_top_md : "35px",
  $searchLabel_textalign_sm : "left",
  $searchLabel_padding_top_sm : "30px",
  $searchLabel_padding_top_xs : "20px",
  $searchLabel_height_lg : "53px",
  $searchLabel_height_md : "70px",
  $searchLabel_height_sm : "62px",
  $searchLabel_height_xs : "52px",
  $searchFontWeight : "700",

  $searchinp_border_top_style: "none",
  $searchinp_border_left_style: "none",
  $searchinp_border_right_style: "none",
  $searchinp_border_bottom_style: "solid",            
  $searchinp_border_top_width: "0px",
  $searchinp_border_left_width: "0px",
  $searchinp_border_right_width: "0px",
  $searchinp_border_bottom_width: "4px",  
  $searchinp_border_top_color: "rgb(51, 51, 51)",
  $searchinp_border_left_color: "rgb(51, 51, 51)",
  $searchinp_border_right_color: "rgb(51, 51, 51)",
  $searchinp_border_bottom_color: "rgb(30, 128, 143)",  
  $searchinp_background_color: "rgb(245, 245, 245)",
  $searchinp_padding_top: "20px",
  $searchinp_padding_right: "0px",
  $searchinp_padding_bottom: "12px",
  $searchinp_padding_left: "0px",
  $searchinp_padding_top_sm: "25px",
  $searchinp_padding_right_sm: "0px",
  $searchinp_padding_bottom_sm: "10px",
  $searchinp_padding_left_sm: "0px",
  $searchinp_padding_top_xs: "20px",
  $searchinp_padding_bottom_xs: "10px",
  $title_background_size : "auto auto",

  //404-500 Error Page
  $errorPage_img_width: "200px",
  $errorPage_img_height: "200px",
  $errorPage_title_color: "rgb(0, 45, 100)",
  $errorPage_title_family: '"RNHouseSansBold", sans-serif',
  $errorPage_text_color: "rgb(51, 51, 51)",
  
  $searchText_padding_top: "0px",
  $searchText_padding_right: "0px",
  $searchText_padding_bottom: "8px",
  $searchText_padding_left: "0px",

  $searchText_padding_top_med: "0px",
  $searchText_padding_right_med: "0px",
  $searchText_padding_bottom_med: "8px",
  $searchText_padding_left_med: "0px",
  $errorPage_searchText_color : "rgb(95, 95, 95)"
   
};

module.exports = {
    props: rbs
}
