var rbs = {
    $primary_2 : "rgba(255, 255, 255, 1)",
    $color_whitesmoke : "rgba(245, 245, 245, 1)",
   // $col_block1_bg:"rgba(181, 0, 89, 1)",
    $col_block1_yellow_bg:"rgba(220, 105, 21, 1)",
    //$font_family_regular: "RNHouseSansBold, sans-serif",
    $font_color_regular:"rgba(40, 0, 32, 1)",
    $primary_white_smoke:"rgba(245, 245, 245, 1)",
    $font_family_regular:"RNHouseSansRegular, sans-serif",
    $font_family_bold:"RNHouseSansLight, sans-serif",    
    $font_family_light:"RNHouseSansLight, sans-serif",
    $font_family_light_ie:'"rnhousesanslight",sans-serif',
    $font_family_text: "RNHouseSansLight, sans-serif",
    $font_family_cta: "RNHouseSansBold, sans-serif",
    $font_weight: "bold",
    $cookie_bgColor: "rgba(40, 0, 32, 1)",
    $cookie_close_color:"rgba(255, 0, 0, 1)",
    $font_family_title:"RNHouseSansLight, sans-serif",
    $body_letter_spacing:"0.3px",
    $impFigText:"rgba(8, 159, 197, 1)",
    $borderbottomcolor:"1px solid rgb(40, 0, 32)",
    $accContmPadding:"55px",
    $acc_contText_color: "rgba(51, 51, 51, 1)",
    $title_color_taskbased:"rgba(255, 255, 255, 1)",
    $errorPage_text_color:"rgba(51, 51, 51, 1)",
    
    
     //toggle variables
    $yellow_toggle_color :"rgb(220, 105, 21, 1)",
    $border_top_left_radius:"100px",
    $border_bottom_left_radius:"100px",
    $border_radius:"1px solid rgba(0, 45, 100, 1)",

    //title wrap rose
    $rose_title_wrap_mt_xl:"40px",
     $rose_title_wrap_mt_xs:"20px",

     //title text
     $font_weight_title_text:"bold",
     //title wrap5 variables
     $title_wrap_mt_xl:"40px",
     $title_wrap_mt_l:"30px",
     $title_wrap_mt_xs:"20px",
     //XL Styles
    $h1_font_size_xl:"46px",
    $h1_line_height_xl:"58px",
    $h2_cust_font_size_xl:"36px",
    $h2_cust_line_height_xl:"46px",
    $h2cust_font_family:"RNHouseSansLight, sans-serif",
    $h2cust_font_weight:"400",
    $h3_font_size_xl:"30px",
    $h3_line_height_xl:"40px",
    $h4_font_size_xl:"22px",
    $h4_line_height_xl:"30px",

    //L Styles
    $h1_font_size_l:"40px",
    $h1_line_height_l:"52px",
    $h2_cust_font_size_l:"36px",
    $h2_cust_line_height_l:"46px",
    $h3_font_size_l:"26px",
    $h3_line_height_l:"36px",
    $h3_cust_font_size_l:"24px",
    $h3_cust_line_height_l:"35px",  

    //M Styles
    $h1_font_size_m:"32px",
    $h1_line_height_m:"42px",
    $h2_cust_font_size_m:"26px",
    $h2_cust_line_height_m:"36px",
    $h3_font_size_m:"24px",
    $h3_line_height_m:"32px",

    //S Styles
    $h1_font_size_s:"32px",
    $h1_line_height_s:"42px",
    $h2_cust_font_size_s:"32px",
    $h2_cust_line_height_s:"42px",
    $h3_font_size_s:"24px",
    $h3_line_height_s:"32px",

    //legal copy styles
    $legal_copy_font_size:"16px",
    $legal_copy_line_height:"26px",
     
 
    //bg color variable
    $main_bg : "rgba(0, 45, 100, 1)",
    $viomain_bg : "rgba(30, 128, 143, 1)",
    $winks_sildertit_font:"RNHouseSansBold, sans-serif",
    $title_f_weight: "bold",
    $dwku_top_xl: "42px",
    $dwku_top_l: "42px",
    $dwku_top_m: "42px",
    $dwku_top_s: "23px",
    
    //primary cta variables
    $cta_bg : "rgba(30, 128, 143, 1)",
    $cta_bor_rad : "100px",
    $cta_lineh : "30px",


     //WINK Variables   
    $stand_alone_title_color : "rgba(40, 0, 32, 1)",
    $winks_sildertit_font:'RNHouseSansLight, sans-serif',
    $winks_text_ff:"RNHouseSansLight, sans-serif",

    /* WINKS xl screen variables */
    $winks_margtop_xl:"35px",
    $winks_display_xl:"block",
    $winks_sildertit_fs_xl:"46px",
    $winks_sildertit_lh_xl:"58px",
    $winks_sildertit_color:"rgb(68, 14, 94)",
    $winks_margtop_item_xl:"39px",
    $winks_slideritem_space:"40px 26px 59px 26px",
    $winks_slideritem_xl_pt:"40px",
    $winks_slideritem_xl_pl:"26px",
    $winks_slideritem_xl_pb:"59px",
    $winks_slideritem_xl_pr:"26px",
    $winks_title_top_xl:"30px",
    $winks_title_fs_xl:"28px",
    $winks_title_lh_xl:"38px",
    $winks_text_fs_xl:"18px",
    $winks_text_lh_xl:"26px",
    $winks_textcolor:"rgba(51, 51, 51, 1)",
    $winks_content_hgt_xl:"188px",
    $winks_slider_col_hgt_xl:"539px",
     //Image Properties
    natwest_image_width:"222px",
    natwest_image_padding:"0px",
    natwest_image_height:"222px",
     //l
    $winks_title_max_h_xl:"76px",
    $winks_title_max_h_l:"70px",
    $winks_title_max_h_m:"62px",
    $winks_title_max_h_s:"62px",
    
    natwest_image_width_l:"182px",
    natwest_image_height_l:"182px",
    natwest_image_width_m:"270px",
    natwest_image_height_m:"270px",
    natwest_image_width_s:"217px",
    natwest_image_height_s:"217px",

    natwest_image_padding_top_m:"40px",
    natwest_image_padding_bottom_m:"20px",
    natwest_image_padding_top_s:"53px",
    natwest_image_padding_bottom_s:"22px",

    natwest_image_theight_xl:"218px",
    natwest_image_theight_l:"267px",
    natwest_image_theight_m:"206px",
    natwest_image_theight_s:"211px",    
    /* WINKS large screen variables */
    $winks_margtop_l:"30px",
    $winks_sildertit_fs_l:"40px",
    $winks_sildertit_lh_l:"56px",
    $winks_margtop_item_l:"29px",
    $winks_slideritem_space_l:"29px 20px 40px 20px",
    $winks_slideritem_l_pt:"29px",
    $winks_slideritem_l_pl:"20px",
    $winks_slideritem_l_pb:"40px",
    $winks_slideritem_l_pr:"20px",
    $winks_title_top_l:"30px",
    $winks_title_fs_l:"25px",
    $winks_title_lh_l:"35px",
    $winks_border_color:"rgba(30, 128, 143, 1)",
    $winks_border_style:"solid",
    $winks_border_width:"1px",
    $winks_content_hgt_l:"236px",
    $winks_slider_col_hgt_l:"518px",
    /* WINKS medium screen variables */
    $winks_margtop_m:"32px",
    $winks_sildertit_fs_m:"32px",
    $winks_sildertit_lh_m:"42px",
    $winks_margtop_item_m:"23px",
    $winks_slideritem_space_m:"23px 0px 0px 0px",
    $winks_slideritem_m_pt:"23px",
    $winks_slideritem_m_pl:"0px",
    $winks_slideritem_m_pb:"0px",
    $winks_slideritem_m_pr:"0px",
    $winks_title_top_m:"41px",
    $winks_title_fs_m:"23px",
    $winks_title_lh_m:"31px",
    $winks_content_hgt_m:"224px",
    $winks_slider_col_hgt_m:"582px",
    /* WINKS small screen variables */
    $winks_margtop_s:"22px",
    $winks_sildertit_fs_s:"32px",
    $winks_sildertit_lh_s:"42px",
    $winks_margtop_item_s:"10px",
    $winks_slideritem_space_s:"20px 0px 0px 0px",
    $winks_slideritem_s_pt:"20px",
    $winks_slideritem_s_pl:"0px",
    $winks_slideritem_s_pb:"0px",
    $winks_slideritem_s_pr:"0px",
    $winks_title_top_s:"30px",
    $winks_title_fs_s:"23px",
    $winks_title_lh_s:"31px",
    $winks_content_hgt_s:"218px",
    $winks_slider_col_hgt_s:"546px",
    $winks_arrows_bg:"rgba(0, 45, 100, 1)",

    //dwku toggle variables
    $tog_bor_rad : "100px 0px 0px 100px",
    $bor_t_l_rad: "100px",
    $bor_b_l_rad: "100px",
    $bor_t_r_rad : "0px",
    $bor_b_r_rad : "0px",
    $tog_bor_rad_right : "0px 100px 100px 0px",

    //why us shelf variables
    $whyus_bg_cocor: "rgba(40, 0, 32, 1)",
    $whyus_twill_height: "0px",
    $whyus_margin_bottom: "20px",
    $whyush3title: "rgba(40, 0, 32, 1)",

     //hero-shelf styles
    $hero_wrap_height_xl:"478px",
    $hero_wrap_height_l:"430px",
    $hero_wrap_height_m:"418px",
    $hero_wrap_height_s:"512px",
    $hero_block_bgColor:"rgba(40, 0, 32, 1)",
    $heroTitleonePaddingTop : "21px",
    $heroTitleonePaddingBtm : "4px",
    $heroTitleonePaddingMdTop : "17px",
    $heroTitleonePaddingMdBtm : "2px",
    $heroTitleonePaddingSmTop : "11px",
    $heroTitleonePaddingSmBtm : "2px",
    $heroTitleonePaddingXsTop : "11px",
    $heroTitleonePaddingXsBtm : "1px",



    //standalone styles
   $font_family_shelf:"RNHouseSansLight, sans-serif",
   $font_weight_shelf:"bold",
   $standalone_title_mt : "10px",
   $standalone_title_mb : "30px",
   $standalone_icon_yellow : "rgb(220, 105, 21)",
   $standalone_icon_pink : "rgb(230, 3, 3)",
   $standalone_icon_width :  "36px",
   $standalone_icon_width_m : "31px",
   $standalone_icon_height :  "35px",
   $standalone_icon_height_m : "30px",
   $standalone_icon_width_s :"24px",
   $standalone_icon_height_s :"24px",
   $standalone_icon_height_s_m :"24x",
   $standalone_icon_height_s_m :"24px",
   $standalone_icon_width_s_xs :"24px",
   $standalone_icon_height_s_xs :"24px",
   $standalone_title_sm : "15px",

   //Get help shelf properties
    $furtherAsstPaddingTop : '75px',
   $furtherAsstPaddingBtm : '101px',
   $furtherAsstPaddingMDBtm : '100px',
   $furtherAsstPaddingSMTop : '75px',
   $furtherAsstPaddingSMBtm : '100px',
   $furtherAsstPaddingXSTop : '88px',
   $furtherAsstPaddingXSBtm : '70px',
   $SearchWrapTop : '38px',
   $SearchWrapBottom : '37px',
   $SearchWrapSmTop : '31px',
   $SearchWrapSmBottom : '20px',
   $SearchWrapXsTop : '22px',
   $SearchWrapXsBottom : '7px',
   $searchBorderColor : 'rgba(51, 51, 51, 1)',
   $searchBorderBtmColor : 'rgba(0, 159, 172, 1)',
   $searchBorderWidth : '0px',
   $searchBorderBtmWidth : '4px',
   $searchBorderStyle : 'none',
   $searchBorderBtmStyle : 'solid',
   $searchRight : '0px',
   $searchTop: '3px',
   $searchSMRight : '0px',
   $searchSMTop : '3px',
   $searchPsuedoFont: '30px',
   $toolMargin : '37px',
   $toolSMMargin : '30px',
   $toolXSMargin : '33px',
   $toolImgSize : '38px',
   $toolImgMDSize : '30px',
   $toolTitleTopMargin: '2px',
   $toolTitleBtmMargin : '0px',
   $toolTitleTopSMMargin : '2px',
   $toolTitleBtmSMMargin : '0px',

   //Contexual links styles
   $context_link_mt_xl : "64px",
   $context_link_mb_xl : "54px",
   $context_link_mt_l   : "68px",
   $context_link_mb_l   : "45px",
   $context_link_mt_m   : "72px",
   $context_link_mb_m   : "47px",
   $context_link_mt_s   : "67px",
   $context_link_mb_s   : "48px",
   $context_menu_link_fs : "18px",
   $context_menu_link_lh : "32px",
   $context_divider_mt_xl : "30px",
   $context_divider_mb_xl : "1px",
   $marginTopAcc : "6px",

   
   //contexual links divider styles
   $context_divider_mt_l : "35px",
   $context_divider_mb_l : "9px",
   $context_divider_mt_m : "32px",
   $context_divider_mb_m : "9px",
   $context_divider_border_color :"4px solid rgb(149, 7, 125)",

   $anchorTestdecoration: 'none solid rgb(0, 45, 100)',
   $anchorBG : 'rgb(30, 128, 143) none repeat scroll 0% 0% / auto padding-box border-box',

   /*Global notifications variables*/
   $notiImageSize : "198px",
   $notiImageMDSize : "158px",
   $notificationBg : "rgba(30, 128, 143, 1)",
   $notiMDPadding : "54px",
   $notiMDPaddingBtm : "50px",
   $notiPaddingLeft : "35px",
   $notiLPaddingLeft : "25px",
   $notiMDPaddingLeft : "0px",
   $CTAMarginBtm : "4px",
   $notiTitleWidth : "446.953px",
   $notiTitleMDWidth : "428.375px",
   $notiTitleSMWidth : "403.188px",
   $notiTextWidth : "633.984px",
   $notiTextMDWidth : "503.984px",
   $notiTextSMWidth : "525px",
   $verticalLineDisp : 'none',
   $notiImageXLMargin: "-24px",
   $notiTransform : "matrix(1, 0, 0, 1, 0, -99)",
   $notiMDTransform : "matrix(1, 0, 0, 1, 0, -79)",
   
   // credit card variables
   $primary_1 :'rgba(40, 0, 32, 1)',
   $primary :'rgba(40, 0, 32, 1)',
   $slider_handle_height_xl : "42px",
   $slider_handle_height_l : "39px",
   $slider_handle_height_sm :"39px",
   $slider_handle_height_xs : "32px",

   // Product details
   $font_color_differ : 'rgba(255, 255, 255, 1)',
  $font_family_product : 'RNHouseSansLight, sans-serif',
   $font_weight_product : '400',

   // For global search XL & L
   $searhBoxWidth_xl:"204px",
   $gsMarginTop : "11px",
   $gsMarginBot: "12px",
   $gsHeight : "auto",
   $gsInputWid : "172px",
   $gsInpPadTop: "9px",
   $gsInpPadBot: "2px",
   $gsInpPadLft:"8px",
   $gsImgWid:"20px",
   $gsImgHgt:"20px",
   $gsImgMarTop:"7px",
   $gsImgMarBot:"6px",
   $gsImgMarRgt:"8px",
   $gsImgMarLft:"4px",
   $gsBorColr:"rgba(0, 159, 172, 1)",
   $gsBorColrBtm:"rgba(30, 128, 143, 1)",
   $gsBorWid:"0px",
   $gsBorWidBot:"3px",
   $gsBorStyle:"none",
   $gsBorStyleBtm:"solid",
   $gsInptFontSize:"14px",
   $gsInptLineHgt:"22px",
   $gsInptTxtColr:"rgba(95, 95, 95, 1)",
   $gsFontFamily:"RNHouseSansRegular, sans-serif",

  // For global search M & S
   $searhBoxWidth_m:"250px",
   $gsMarginTop_m : "6px",
   $gsMarginBot_m: "8px",
   $gsMarginLft_m : "5px",
   $gsMarginRgt_m: "5px",
   $gsHeight_m : "auto",
   $gsInputWid_m : "194px",
   $gsInpPadTop_m: "7px",
   $gsInpPadBot_m:"2px",
   $gsInpPadlft_m:"7px",
   $gsImgMarTop_m:"6px",
   $gsImgMarBot_m:"5px",
   $gsImgMarLft_m:"10px",
   $gsImgMarRgt_m:"5px",

   //product Listing 
   $productIncomeClr: "rgba(149, 7, 125, 1)",
   $productH3font_26: "26px",
   $productH3lh: "37px",
   $productButton : "rgba(30, 128, 143, 1)",
   $productH3Color : "rgba(40, 0, 32, 1)",
   $productImg_s : "179px",
   $productImg_m : "146px",
   $h4Cust_font_size_xl:"20px",
   $h4Cust_line_height_xl:"30px",
   $h4Cust_font_size_l:"20px",
   $h4Cust_line_height_l:"30px",
   $h4Cust_font_size_m:"18px",
   $h4Cust_line_height_m:"26px",
   $h4Cust_font_size_s:"18px",
   $h4Cust_line_height_s:"26px",
   $font_family_singleTitleH4:"RNHouseSansRegular, sans-serif",
   $font_family_singleTitleContent: "RNHouseSansRegular, sans-serif",
   $productSelfLiColor:"rgb(40, 0, 32)",
   $productSingleShelfMarBot:"0px",
   $productMultipleShelfProps:"0px",
   $buttonTextFontFam:"RNHouseSansBold, sans-serif",

   $productShelfImgPropsWidth: "24px",
   $productShelfImgPropsHeight: "24px",
   $singleContentCTAbMarBot: "30px",

   $h3Cust_font_size_xl:"26px",
   $h3Cust_line_height_xl:"34px",
   $h3Cust_font_size_l:"24px",
   $h3Cust_line_height_l:"35px",
   $h3Cust_font_size_ms:"24px",
   $h3Cust_line_height_ms:"32px",

   $productTitleH2_m : '20px',
   $productTitleH2_xs : '20px',

   $productShelf_pt_xl : '35px',
   $productShelf_pt_m : '30px',
   $productShelf_pb_m : '30px',
   $productShelf_pt_xs : '30px',
   $productShelf_pb_xs : '50px',
   $productSelfImg_w : '30px',
   $productSelfImg_h : '29px',
   $productSelfLiSquare : '0px',
   $font_family_bold_2:"RNHouseSansRegular, sans-serif",
   $productSelfCtaTop_xl: '35px',
   $productSelfCtaTop_m: '30px',
   $productMultiImg_s: '169px', 
   //Article shelf  
   $bg_color : 'rgb(181, 0, 89, 1)',
    //footer-component-variables
  
    $footer_bg_color :"rgba(40, 0, 32, 1)",
   $footer_bg_image : "none",  

   //product-detail shelf
   $productDetail_tabBgColor : "rgba(149, 7, 125, 1)",

   //imp fig shelf variables
   $winks_textcolor:"rgba(51, 51, 51, 1)",

   //single article shelf 
   $shelf_Padding_Bottom: "30px",

   //download shelf
   $padding_top: "30px",
   $padding_bottom: "50px",
   $padding_topM: "30px",
   $padding_bottomM: "50px",
   $padding_topS: "30px",
   $padding_bottomS: "50px",
   $padding_topXS: "30px",
   $padding_bottomXS: "50px",
  $download_nopadding: "0px",

   $titleWrapper_margin_top_lg: "4px",
   $titleWrapper_margin_top_xs: "11px",

   $link_margin_bottom: "20px",

   //toggle shelf
   $bgColor : "rgba(105, 67, 150, 1)",
   $border_top_left_radius: "100px",
   $border_top_right_radius: "0px",
   $border_bottom_left_radius: "100px",
   $border_bottom_right_radius: "0px",

   $EvenTogg_border_top_left_radius: "0px",
   $EvenTogg_border_top_right_radius: "100px",
   $EvenTogg_border_bottom_left_radius: "0px",
   $EvenTogg_border_bottom_right_radius: "100px",
 

   $cta_padding_top: "10px",
   $cta_padding_right: "20px",
   $cta_padding_bottom: "10px",
   $cta_padding_left: "20px",

   //pre-apply business 
   $shelf_bg_color: "rgba(111, 44, 145, 1)",
   $singleArticle_padding_bottom: "30px",

   //header  Section
   $header_bg_color : "rgba(10,47,100, 1)",
   $L2text_color  : "rgba(0, 126, 166,1)",

   //campaign promo
  $cp_primarycta_top_margin_xl: "20px",
  $cp_cta_padding_top: "10px",
  $cp_cta_padding_right: "20px",
  $cp_cta_padding_bottom: "10px",
  $cp_cta_padding_left: "20px",
  $cp_font_color : "rgba(149, 7, 125, 1)",

   //breadcrumb links
   $linkcolor : "rgba(30, 128, 143, 1)",
   $linkborderbottom : "1px solid rgb(30, 128, 143)",
   $currentlink : "rgba(40, 0, 32, 1)",
   //table shelf
   $heading_max_height: "60px",
   $image_margin_right: "13px",
   $table_shelf_font_color : "rgba(40, 0, 32, 1)",
   $table_shelf_dd_font_color : "rgba(40, 0, 32, 1)",
   $text_padding_left: "39px",
    $table_shelf_textcolor:"rgba(51, 51, 51, 1)",

//single listing complaince
   $area_padding_top : "20px",
   $area_padding_bottom : "0px",

    //needbased panel
  $taskBased_bgColor : "rgba(245, 245, 245, 1)", 
  $taskpanel_pad_bottom : "20px",
  $taskpanel_pad_bottom_med : "20px",
  $title2Background : "rgba(112, 116, 121, 0.76)",
  $taskpanel_paddingL:"4px",
  $taskpanel_paddingM:"2px",
  $taskpanel_paddingS:"0px",
  $taskpanel_paddingXS:"4px",
  $PadtopL:"21px",
  $taskpanelTit:"20px",
  $taskpanelTitXS:"17px",
  $taskpanelTitBottomL:"5px",
  $taskpanelTitBottomM:"2px",
  $taskpanelTitBottomS:"0px",
  $taskpanelTitBottomXS:"0px",
  $taskpanelTitLeft:"16px",
  $taskpanelTitRight:"16px",
  $taskpanelSpanTit1LM:"-9px",
  $taskpanelSpanTit1M:"-9px",
  $taskpanelSpanTit1S:"-7px",
  $taskpanelSpanTit1XS:"-7px",
  $taskpanelSpanTit2L:"-9px",
  $taskpanelSpanTit2M:"-9px",
  $taskpanelSpanTit2S:"-7px",
  $taskpanelSpanTit2LXS:"-9px",
  $taskpanelTopM:"2px",
  $taskpanelTopS:"4px",
  $taskpanelTopXS:"4px",
  $taskpanelLineHeightM:"56px",
  $title_background_color:"rgba(149, 7, 125, 0.6)",


  $img_margin_left_right_lg : "43px",
  $img_width_height_lg : "88px",
  $img_margin_left_right_md : "23px",
  $img_width_height_md : "88px",
  $img_margin_left_right_sm : "11px",
  $img_width_height_sm : "88px",

  $cta_padding_top : "10px",

  $searchWrap_padding_bottom : "35px",
  $search_bg_color : "rgba(245, 245, 245, 1)",
  $searchWrap_padding_bottom_sm : "30px",
  $searchWrap_padding_bottom_xs : "20px",

  $searchLabel_float_lg : "none",
  $searchLabel_margin_rt_lg : "0px",
  $searchLabel_margin_bottom_sm : "0px",
  $searchLabel_padding_top_lg : "15px",
  $searchLabel_padding_top_md : "35px",
  $searchLabel_textalign_sm : "left",
  $searchLabel_padding_top_sm : "30px",
  $searchLabel_padding_top_xs : "20px",
  $searchLabel_height_lg : "53px",
  $searchLabel_height_md : "70px",
  $searchLabel_height_sm : "62px",
  $searchLabel_height_xs : "52px",
  $searchFontWeight : "700",

  $searchinp_border_top_style: "none",
  $searchinp_border_left_style: "none",
  $searchinp_border_right_style: "none",
  $searchinp_border_bottom_style: "solid",            
  $searchinp_border_top_width: "0px",
  $searchinp_border_left_width: "0px",
  $searchinp_border_right_width: "0px",
  $searchinp_border_bottom_width: "4px",  
  $searchinp_border_top_color: "rgba(51, 51, 51, 1)",
  $searchinp_border_left_color: "rgba(51, 51, 51, 1)",
  $searchinp_border_right_color: "rgba(51, 51, 51, 1)",
  $searchinp_border_bottom_color: "rgba(8, 159, 197, 1)",  
  $searchinp_background_color: "rgba(245, 245, 245, 1)",
  $searchinp_padding_top: "20px",
  $searchinp_padding_right: "0px",
  $searchinp_padding_bottom: "12px",
  $searchinp_padding_left: "0px",
  $searchinp_padding_top_sm: "25px",
  $searchinp_padding_right_sm: "0px",
  $searchinp_padding_bottom_sm: "10px",
  $searchinp_padding_left_sm: "0px",
  $searchinp_padding_top_xs: "20px",
  $searchinp_padding_bottom_xs: "10px",
  $title_background_size : "auto",

  //incident Notification
   $incident_bg_color : "rgba(29, 123, 138, 1)",
   $incident_ptop : "54px",
   $incident_pbottom : "30px",
   $incident_title_family : "RNHouseSansLight, sans-serif",

   //Completion Prompt shelf
    $completionprompt_image_size : "198px",
    $completionprompt_image_size_l : "158px",
    $completionprompt_content_pl : "36px",
    $completionprompt_content_pl_l :"25px",
    $completionprompt_rte_color : "rgba(51, 51, 51, 1)",
    $completionprompt_FontFamily : "RNHouseSansLight, sans-serif",
    $primCta_background : "rgba(30, 128, 143, 1)",
    $verticalLine_background : "rgba(216, 216, 216, 1)",
    $completionprompt_topL : "142px",
    $completionprompt_topM : "150.5px",
    $background_completionPrompt:"linear-gradient(transparent calc(100% - 1px), rgb(30, 128, 143) 10px, rgb(30, 128, 143))",
    $completionprompt_rteFontFamily : "RNHouseSansLight, sans-serif",
    $completion_primCTA_pb : "10px",
    $completion_primCTA_pt : "10px",
    $completion_secCTA_margin : "10px",
    $completion_secCTA_color : "rgba(30, 128, 143, 1)",
  //actionable-content variables
  $act_cont_grey_color_on_white_bg :"rgba(245, 245, 245, 1)", //grey
  $act_cont_grey_color_on_Brand_bg : "rgba(40, 0, 32, 1)",  //premium
  $fill_color_on_brand_bg :"rgb(255, 255, 255)",         //white
  $fill_color_on_white_bg : "rgb(40, 0, 32)",
  $actContTitleColoronWhiteBg : "rgba(40, 0, 32, 1)",
  $actContTitleColoronBrandBg :  "rgba(255, 255, 255, 1)",
  $actContTextColoronWhiteBg : "rgba(51, 51, 51, 1)",
  $actContCTAColor : "rgba(30, 128, 143, 1)",
  $regular_font_family: 'RNHouseSansRegular, sans-serif',
  $light_font_family: 'RNHouseSansLight, sans-serif',
  $bold_font_family: 'RNHouseSansBold, sans-serif',
  $primaryCTAFontFamily : 'RNHouseSansBold, sans-serif'
};

module.exports = {
    props: rbs
}
